# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-06 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180705_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valuemachine',
            old_name='run_server',
            new_name='run_service',
        ),
        migrations.AddField(
            model_name='physicalmachine',
            name='brand',
            field=models.CharField(max_length=45, null=True, verbose_name='\u54c1\u724c'),
        ),
        migrations.AddField(
            model_name='physicalmachine',
            name='run_service',
            field=models.CharField(max_length=124, null=True, verbose_name='\u8fd0\u884c\u670d\u52a1'),
        ),
    ]
