# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180709_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='0.0.0.0', max_length=124, verbose_name='')),
                ('is_del', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='0.0.0.0', max_length=124, verbose_name='')),
                ('end', models.CharField(default='0.0.0.0', max_length=124, verbose_name='')),
                ('subnet_mask', models.CharField(default='24', max_length=124, verbose_name='')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='')),
                ('is_del', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.NetworkSegment'),
        ),
    ]
