# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-16 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=45, verbose_name='')),
                ('status', models.BooleanField(default=False)),
                ('level', models.CharField(default='0', max_length=30, null=True, verbose_name='')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
    ]
