# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-23 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-pk']},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='info',
            new_name='title',
        ),
    ]
