# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=30, verbose_name='\u4e1a\u52a1\u7ebf\u540d')),
                ('manager', models.CharField(default='shawna', max_length=30, null=True, verbose_name='\u4e1a\u52a1\u5bf9\u63a5\u4eba')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('business', models.CharField(max_length=45, null=True, verbose_name='\u4e1a\u52a1\u8303\u56f4')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='\u63cf\u8ff0')),
                ('is_del', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
