# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-17 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20180716_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
