# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20180709_1417'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=45, verbose_name='')),
                ('status', models.BooleanField(default=False)),
                ('level', models.CharField(default='0', max_length=30, null=True, verbose_name='')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='web', max_length=30, verbose_name='\u9879\u76ee\u540d')),
                ('language', models.CharField(choices=[('0', 'Java'), ('1', 'Python'), ('2', 'Other'), ('3', 'PhP')], default='1', max_length=30, verbose_name='\u8bed\u8a00')),
                ('develop', models.CharField(max_length=45, null=True, verbose_name='\u5f00\u53d1\u4eba\u5458')),
                ('develop_contact', models.CharField(max_length=45, null=True, verbose_name='\u5f00\u53d1\u8054\u7cfb\u65b9\u5f0f')),
                ('ops_contact', models.CharField(max_length=45, null=True, verbose_name='\u8fd0\u7ef4\u8054\u7cfb\u65b9\u5f0f')),
                ('desc', models.CharField(max_length=256, null=True, verbose_name='\u63cf\u8ff0')),
                ('is_del', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='businessline',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='project',
            name='business_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BusinessLine'),
        ),
        migrations.AddField(
            model_name='project',
            name='physical_machine',
            field=models.ManyToManyField(to='assets.PhysicalMachine'),
        ),
        migrations.AddField(
            model_name='project',
            name='value_machine',
            field=models.ManyToManyField(to='assets.ValueMachine'),
        ),
    ]
