# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_machineroom_has_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='machineroom',
            name='has_cabinet',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machineroom',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='physicalmachine',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='valuemachine',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
