# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180705_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
