# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-09 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20180706_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmachine',
            name='disk_array',
            field=models.CharField(choices=[('1', 'raid0'), ('2', 'raid1'), ('3', 'raid5'), ('4', 'raid10'), ('5', 'raid5+\u70ed\u5907'), ('6', 'other')], default='6', max_length=30, verbose_name='\u78c1\u76d8\u9635\u5217'),
        ),
    ]
