# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-24 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_ipaddress_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksegment',
            name='idc',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='assets.MachineRoom'),
            preserve_default=False,
        ),
    ]
